### ISSUE TITLE
How to access the ObjectManager

### ISSUE THREAD

**Issue by satirebird** [igo95862/python-sdbus#2]
I tried to use the library to get access to the bluetooth devices. In the [examples](https://stackoverflow.com/questions/38953175/connect-to-a-bluetooth-le-device-using-bluez-python-dbus-interface) you need to get all objects from the object manager. Is there a way to get that from the sdbus library? 
The official documentation of the ObjectManager can be found [here](https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces-objectmanager)

**Comment by igo95862** [comment]
The `/org/freedesktop/NetworkManager` objects has the `devices` property https://github.com/igo95862/python-sdbus/blob/98e71bca4fa3ab73da8e7a46b4e1241d22e4c141/interfaces/networkmanager/sdbus_block/networkmanager/interfaces_other.py#L1070

which returns the list of paths to device dbus objects.

BTW I have not finished the Network Manager binds. They are not published on PyPI or AUR. If you want to try them you will have to run from source.

**Comment by satirebird** [comment]
The 'org.bluez' doesn't have such a property. You have to get the list of all objects from 'org.bluez' (using the ObjectManager) and check which one has an interface with the name 'org.bluez.Adapter1'. Then you can go further and e.g. start the bluetooth scan for a given adapter.

**Comment by igo95862** [comment]
`org.bluez` is NOT NetworkManager

**Comment by igo95862** [comment]
I added `DbusInterfaceCommonWithManager` and `DbusInterfaceCommonWithManagerAsync` classes that allow access to ObjectManager interface. 

Should be something like this using blocking interface on repl loop:
```
>>> import sdbus
>>> t = sdbus.DbusInterfaceCommonWithManager('org.bluez.obex', '/')
>>> t.get_managed_objects()
{'/org/bluez/obex': {'org.freedesktop.DBus.Introspectable': {}, 'org.bluez.obex.AgentManager1': {}, 'org.bluez.obex.Client1': {}}}
```

**Comment by igo95862** [comment]
I renamed the object manager interfaces to `DbusObjectManagerInterface` and `DbusObjectManagerInterfaceAsync`

**Comment by igo95862** [comment]
Binary packages solve all issues with libsystemd incompatibilities.
