### ISSUE TITLE
undefined symbol: sd_bus_object_path_is_valid

### ISSUE THREAD

**Issue by satirebird** [igo95862/python-sdbus#3]
Importing the library fails in Ubuntu 20.04 LTS
Python version is 3.8.5
Steps to reproduce:
```
sudo apt install build-essential python3-venv python3-dev
sudo apt install libsystemd-dev
mkdir sdbus-test
cd sdbus-test/
python3 -m venv venv
source ./venv/bin/activate
pip install wheel
pip install sdbus
```
The installation works perfectly. Trying to use the library failed with:
```
>>> from sdbus import DbusInterfaceCommon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sven/sdbus-test/venv/lib/python3.8/site-packages/sdbus/__init__.py", line 21, in <module>
    from .dbus_common import (get_default_bus, request_default_bus_name_async,
  File "/home/sven/sdbus-test/venv/lib/python3.8/site-packages/sdbus/dbus_common.py", line 27, in <module>
    from .sd_bus_internals import SdBus, sd_bus_open
ImportError: /home/sven/sdbus-test/venv/lib/python3.8/site-packages/sdbus/sd_bus_internals.cpython-38-x86_64-linux-gnu.so: undefined symbol: sd_bus_object_path_is_valid
```

**Comment by igo95862** [comment]
It was added in to sd-bus on 2020-05-25 https://github.com/systemd/systemd/commit/d2916409edb7bea9963c71052375a9919df28dc1 and did not make it in Ubuntu 20.04 LTS.

I've made a mistake of building against the latest version on Arch Linux instead of sticking to some LTS version like Ubuntu. However, I think I will fix it and setup a CI to build on Ubuntu 20.04.

**Comment by igo95862** [comment]
I pushed more commits for compatibility with Ubuntu 20.04 https://github.com/igo95862/python-sdbus/commit/ee56d87972b4a0fbaa948fa3159a90cbbe1ed851 https://github.com/igo95862/python-sdbus/commit/ff0c1a4b5a060866579fb6df15ea3ccf3a8ca401

Just tested on Ubuntu 20.04 docker image.

You need following packages `python3 gcc python3-setuptools python3-dev libsystemd-dev`

If you want to run unit tests you will also need: `python3-jinja2 systemd dbus`

Can you test it if it works for you? I will close the issue if it does.

**Comment by igo95862** [comment]
Installing on Ubuntu from source seems to require `--old-and-unmanageable` for some reason. Otherwise the namespace packages `sdbus_block` and `sdbus_async` won't work.

**Comment by igo95862** [comment]
I uploaded release candidate to PyPI with latest fixes. You should be able to install it with `pip3 install sdbus==0.8.0rc1`

**Comment by igo95862** [comment]
Binary packages solve all issues with libsystemd incompatibilities.
